"""Set cascade deletion

Revision ID: ed51aa9da05e
Revises: a99bbd095fa9
Create Date: 2024-03-23 15:06:36.245916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed51aa9da05e'
down_revision = 'a99bbd095fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_category_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('image_document_id_fkey', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_document_id_fkey', 'image', 'document', ['document_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_category_id_fkey', 'document', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
